# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 12:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_dataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('filename', models.FileField(upload_to='folder/')),
            ],
        ),
    ]
