# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 12:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_geographic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('columns', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('filename', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Geographic',
        ),
    ]
