# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_auto_20190512_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geography',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='version',
        ),
        migrations.DeleteModel(
            name='Geography',
        ),
    ]
